import subprocess
import requests
from bs4 import BeautifulSoup
import pandas as pd

chrome_path = "/usr/bin/google-chrome"

# Lista de filmes:
filmes = ['13 Exorcismos',
 '65 - Ameaça Pré-Histórica',
 '97 Minutos',
 'A Alma Quer Voar',
 'A Baleia',
 'A Bela América',
 'A Casa Dos Prazeres',
 'A Chamada',
 'A Cidade Dos Abismos',
 'A Era De Ouro',
 'A Era Dos Humanos',
 'A Esposa De Tchaikovsky',
 'A Estranha Comédia Da Vida',
 'A Fada Do Dente',
 'A Filha Do Rei Do Pântano',
 'A Força Da Amizade',
 'A Freira 2',
 'A História Da Minha Mulher',
 'A Ilha Dos Ilús',
 'A Lasanha Assassina - A Revolta Das Massas',
 'A Linha',
 'A Maldição Do Queen Mary',
 'A Menina Silenciosa',
 'A Morte Do Demônio: A Ascensão',
 'A Noite Das Bruxas',
 'A Noite Do Dia 12',
 'A Pequena Sereia',
 'A Porta Ao Lado',
 'A Praga',
 'A Primeira Comunhão',
 'A Primeira Morte De Joana',
 'A Profecia Do Mal',
 'A Ruptura',
 'A Sindicalista',
 'A Sociedade Da Neve',
 'A Terra Negra Dos Kawa',
 'A Última Festa',
 'A Última Rainha',
 'A Viagem Encantada',
 'Afire',
 'After Para Sempre',
 'Air: A História Por Trás Do Logo',
 'Aldeia Natal',
 'Além De Nós',
 'Além Do Tempo',
 'Alerta Máximo',
 'Alma Viva',
 'Almas Gêmeas',
 'Amor(Es) Verdadeiro(S)',
 'Andança - Os Encontros E As Memórias De Beth Carvalho',
 'Angela',
 'Ao Seu Lado',
 'Aquaman 2: O Reino Perdido',
 'As 8 Montanhas',
 'As Aventuras De Poliana - O Filme',
 'As Historias De Meu Pai',
 'As Marvels',
 'As Múmias E O Anel Perdido',
 'As Órfãs Da Rainha',
 'As Quatro Irmãs',
 'As Tartarugas Ninja: Caos Mutante',
 'As Três Vidas De Frieda Wolff',
 'As Visões De Ramses',
 'As Vitórias-Régias De Monet',
 'Assassinos Da Lua Das Flores',
 'Asteroid City',
 'Atiraram No Pianista',
 'Ato Final',
 'Babilônia',
 'Bala Sem Nome',
 'Barbie',
 'Barraco De Família',
 'Batem À Porta',
 'Beau Tem Medo',
 'Belas Promessas',
 'Belchior - Apenas Um Coração Selvagem',
 'Belo Desastre',
 'Bem Vindos De Novo',
 'Bem-Vinda Violeta',
 'Besouro Azul',
 'Biocêntricos',
 'Blackberry',
 'Blue Jean',
 'Bons Companheiros',
 'Boogeyman: Seu Medo É Real',
 'Brado',
 'Brichos 3 - Megavirus',
 'Broker - Uma Nova Chance',
 'Cafi',
 'Campeões',
 'Canção Ao Longe',
 'Capitu E O Capitulo',
 'Casa Vazia',
 'Casamento Em Família',
 'Casamento Grego 3',
 'Chef Jack, O Cozinheiro Aventureiro',
 'Cidade Rabat',
 'Close',
 'Coisas Do Amor',
 'Coração De Neon',
 'Coração De Padre - São José',
 'Corpolítica',
 'Corsage',
 'Creed Iii',
 'Criaturas Do Senhor',
 'Crônica De Uma Cidade Partida',
 'Culpa E Desejo',
 'Dançando No Silêncio',
 'David Contra Os Bancos',
 'De Volta À Córsega',
 'Decisão De Partir',
 'Deixados Para Trás: O Início Do Fim',
 'Demon Slayer: To The Swordsmith Village',
 'Depois De Ser Cinza',
 'Derrapada',
 'Desaparecida',
 'Desapega',
 'Desejo Proibido',
 'Despedida',
 'Destino Das Sombras',
 'Destinos Opostos',
 'Diga O Que Quiser! Eu Vou Ser Feliz A Beça!',
 'Digimon Adventure 02: The Beginning',
 'Dinheiro Fácil',
 'Disco Boy',
 'Do Jeito Que Elas Querem - O Próximo Capítulo',
 'Dos 3 Aos 3',
 'Drácula - A Última Viagem Do Demeter',
 'Duas Bruxas - A Herança Diabólica',
 'Dungeons & Dragons: Honra Entre Rebeldes',
 'Eami',
 'Elas Por Elas',
 'Elementos',
 'Elis & Tom, Só Tinha De Ser Com Você',
 'Emily',
 'Empate',
 'Enaldinho E O Mistério Da Lagoa.',
 'Eneida',
 'Entre Mulheres',
 'Eo',
 'Espera',
 'Esquema De Risco: Operação Fortune',
 'Estados Unidos Do Brasil',
 'Estranha Forma De Vida Versão Estendida',
 'Eu Deveria Estar Feliz',
 'Eu Sou Maria',
 'Eu, Leonardo Da Vinci',
 'Evolution',
 'Fale Comigo',
 'Feriado Sangrento',
 'Fervo',
 'Fim De Semana No Paraíso Selvagem',
 "Five Nights At Freddy'S - O Pesadelo Sem Fim",
 'Fluxo',
 'Folhas De Outono',
 'Franco No Trem Do Medo',
 'Garota Radiante',
 'Garoto Dos Céus',
 'Gato De Botas 2: O Último Pedido',
 'Gatos No Museu',
 'Gauguin No Taiti',
 'Gemini: O Planeta Sombrio',
 'Godzilla Minus One',
 'Golda - A Mulher De Uma Nação',
 'Gran Turismo - De Jogador A Corredor',
 'Guardiões Da Galáxia Vol. 3',
 'Guerra Entre Herdeiros',
 'Herói De Sangue',
 'Holy Spider',
 'Homem-Aranha: Através Do Aranhaverso',
 'Homem-Formiga E A Vespa: Quantumania',
 'How To Have Sex',
 'Hypnotic - Ameaça Invisível',
 'I Wanna Dance With Somebody – A História De',
 'Il Boemo',
 'Incompatível Com A Vida',
 'Indiana Jones E A Relíquia Do Destino',
 'Ithaka - A Luta De Assange',
 'Jair Rodrigues - Deixa Que Digam',
 'J-Hope In The Box',
 'Jogos Mortais X',
 'Jogos Vorazes – A Cantiga Dos Pássaros E Das',
 'John Wick 4: Baba Yaga',
 'Jornada Para Belem',
 'La Parle',
 'La Situación',
 'Leonora, Adeus',
 'Linha De Frente',
 'Lobo E Cão',
 'Los Delincuentes',
 'Loucas Em Apuros',
 'Luiz Carlini - Guitarrista De Rock',
 'Luz Nos Trópicos',
 'M3Gan',
 'Mãe',
 'Maestro',
 'Mafia Mamma – De Repente Criminosa',
 'Mamonas Assassinas O Filme',
 'Mansão Mal-Assombrada',
 'Máquina Do Desejo',
 'Mares Do Desterro',
 'Marinheiro Das Montanhas',
 'Mato Seco Em Chamas',
 'Mavka - Aventura Na Floresta',
 'Me Chama Que Eu Vou',
 'Medusa',
 'Medusa Deluxe',
 'Megatubarão 2',
 'Memória Sufocada',
 'Mesmo',
 'Meu Nome É Gal',
 'Meu Novo Brinquedo',
 'Meu Pai É Um Perigo',
 'Meu Vizinho Adolf',
 'Michelangelo - Infinito',
 'Minha Irmã E Eu',
 'Mirante',
 'Missão Antena: Uma Aventura Intergaláctica',
 'Missão De Sobrevivência',
 'Missão: Impossível - Acerto De',
 'Miúda E O Guarda-Chuva',
 'Môa, Raiz Afro Mãe',
 'Monster',
 'Morte A Pinochet',
 'Muleque',
 'Muribeca',
 'Mussum, O Filmis',
 'Muti - Rituais Mortais',
 'Não Abra!',
 'Não Sei Quantas Almas Tenho',
 'Não Tem Volta',
 'Napoleão',
 'Nardjes A.',
 'Nas Ondas Da Fé',
 'Natureza Morta',
 'Nefarious',
 'Nelson Pereira Dos Santos - Vida De Cinema',
 'Nina: A Heroína Dos Sete Mares',
 'Ninguém É De Ninguém',
 'Nintendo E Eu',
 'Niobe',
 'Noites Alienígenas',
 'Nossa Senhora Do Nilo',
 'Nosso Amigo Extraordinário',
 'Nosso Sonho',
 'Nostalgia',
 'Nyad',
 'O Acidente',
 'O Alecrim E O Sonho',
 'O Amor Mandou Mensagem',
 'O Ano Do Tigre',
 'O Assassino',
 'O Ceu',
 'O Chamado 4: Samara Ressurge',
 'O Circo Voltou',
 'O Colibri',
 'O Convento',
 'O Crime É Meu',
 'O Demônio Dos Mares',
 'O Desafio De Marguerite',
 'O Espaço Infinito',
 'O Exorcista - O Devoto',
 'O Exorcista Do Papa',
 'O Grande Mauricinho',
 'O Homem Cordial',
 'O Homem De Lagoa Santa',
 'O Jogo Da Invocação',
 'O Livro Dos Sonhos',
 'O Lodo',
 'O Malvado - Horror No Natal',
 'O Menino E O Tigre',
 'O Mestre Da Fumaça',
 'O Nascimento Do Mal',
 'Ó Paí, Ó 2',
 'O Pastor E O Guerrilheiro',
 'O Pequeno Corpo',
 'O Pior Vizinho Do Mundo',
 'O Portal Secreto',
 'O Porteiro',
 'O Protetor - Capítulo Final',
 'O Rio Do Desejo',
 'O Senhor Do Caos',
 'O Sequestro Do Voo 375',
 'O Silêncio Da Vingança',
 'O Último Chamado De Maria',
 'O Último Dia De Yitzhak Rabin',
 'O Último Ônibus',
 'O Ursinho Pooh: Sangue E Mel',
 'O Urso Do Pó Branco',
 'Oferenda Ao Demônio',
 'Olha Pra Elas',
 'Olhos Famintos: Renascimento',
 'Onde Fica Esta Rua? Ou Sem Antes Nem Depois',
 'Operação Hunt',
 'Oppenheimer',
 'Os Aventureiros - A Origem',
 'Os Banshees De Inisherin',
 'Os Cavaleiros Do Zodíaco - Saint Seiya - O Começo',
 'Os Fabelmans',
 'Os Filhos Dos Outros',
 'Os Mercenários 4',
 'Os Peludos',
 'Os Segredos Do Universo',
 'Os Três Mosqueteiros: D’Artagnan',
 'Os Três Mosqueteiros: Milady',
 'Osmar, A Primeira Fatia Do Pão De Forma - O Filme',
 'Pacifiction',
 'Pânico Vi',
 'Para Onde Voam As Feiticeiras',
 "Para'Í",
 'Pare Com Suas Mentiras',
 'Passages',
 'Patrulha Canina: Um Filme Superpoderoso',
 'Pearl',
 'Pedágio',
 'Pele',
 'Perdida',
 'Perlimps',
 'Pérola',
 'Pessoas Humanas',
 'Plauto, Um  Sopro Musical',
 'Por Trás Da Linha De Escudos',
 'Poropopó',
 'Presos Na Floresta',
 'Propriedade',
 'Puan',
 'Quando Falta O Ar',
 'Quantos Dias. Quantas Noites',
 'Que Horas Eu Te Pego ?',
 'Quem Fizer Ganha',
 'Rama Pankararu',
 'Raquel 1:1',
 'Razões Para Não Ser Mãe',
 'Reflexão',
 'Regra 34',
 'Remoção',
 'Renfield: Dando Sangue Pelo Chefe',
 'Resistência',
 'Retratos Fantasmas',
 'Revolta Dos Malês',
 'Rheingold',
 'Rio Doce',
 'Rio, Negro',
 'Roberto Farias:  Memórias De Um Cineasta',
 'Rock Dog: Uma Batida Animal',
 'Rodeio Rock',
 'Rodeo',
 'Ruby Marinho - Monstro Adolescente',
 'Ruim Pra Cachorro',
 'Samsara, A Jornada Da Alma',
 'São Miguel Arcanjo - O Anjo Maior',
 'Sede Assassina',
 'Segredos De Guerra',
 'Segundo Tempo',
 'Sem Ar',
 'Sem Deixar Rastros',
 'Sem Ursos',
 'Seu Amor De Volta',
 'Seus Ossos E Seus Olhos',
 'Shazam! Fúria Dos Deuses',
 'Sinfonia De Um Homem Comum',
 'Skinamarink',
 'Sobrenatural: A Porta Vermelha',
 'Softie',
 'Som Da Liberdade',
 'Sombras De Um Crime',
 'Stand Up Minha Vida É Uma Piada',
 'Suga: Road To D-Day',
 'Super Mario Bros. - O Filme',
 'Suzume',
 'Sword Art Online Progressive:',
 'Tá Escrito',
 'Tár',
 'Tempos De Barbárie - Ato I: Terapia Da Vingança',
 'Tenho Fé',
 'Terra De Deus',
 'The First Slam Dunk',
 'The Five Devils',
 'The Flash',
 'Tia Virgínia',
 'Till - A Busca Por Justiça',
 'Tinnitus',
 'Tire 5 Cartas',
 'Toc Toc Toc: Ecos Do Além',
 'Tolos São Os Outros',
 'Tpm! Meu Amor',
 'Tração',
 'Transformers: O Despertar Das Feras',
 'Três Mulheres - Uma Esperança',
 'Três Tigres Tristes',
 'Triângulo Da Tristeza',
 'Trolls 3 - Juntos Novamente',
 'Tudo Sob Descontrole',
 'Um Dia Cinco Estrelas',
 'Um Dia Nossos Segredos Serão Revelados',
 'Um Filho',
 'Um Filme De Cinema',
 'Um Jóquei Cearense Na Coreia',
 'Um Pouco De Mim, Um Pouco De Nós',
 'Um Samurai Em São Paulo',
 'Uma Carta Para Papai Noel',
 'Uma Fada Veio Me Visitar',
 'Uma Família Extraordinária',
 'Uma Noite Em Haifa',
 'Uma Vida Sem Ele',
 'Urubus',
 'Uýra – A Retomada Da Floresta',
 'Vai Corinthians!',
 'Vai E Vem',
 'Vai Ter Troco',
 'Van Gogh: Campos De Trigo E Céus Nublados',
 'Velozes E Furiosos 10',
 'Vento Na Fronteira',
 'Vidas Descartáveis',
 'Wonka']

filmes = [filme.replace('-',':') for filme in filmes] # Trocar - por : nos nomes dos filmes

## Loop para localizar o filme no IMDB:
urls=[]

for filme in filmes:
    if ' ' in filme:
        filme = filme.replace(' ', "%20")
        url = f'https://www.imdb.com/find?q={filme}'
        urls.append(url)
        #subprocess.run([chrome_path, url])
    else:
        url = f'https://www.imdb.com/find?q={filme}'
        urls.append(url)
        #subprocess.run([chrome_path, url])


## Loop para encontrar a página exata do filme:
titulos = []

cabecalho = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'
 }

for i,url in zip(range(0, len(urls)), urls):
    pagina = url
    resposta = requests.get(pagina, headers=cabecalho)
    soup = BeautifulSoup(resposta.content, 'html.parser')
    nomes = soup.find_all('a', {'class': 'ipc-metadata-list-summary-item__t'})
    nomes = [nome.get_text().title() for nome in nomes]
    if nomes.count(filmes[i])==1:
        index_nome = nomes.index(filmes[i])
        nomes = soup.find_all('a', {'class': 'ipc-metadata-list-summary-item__t'})
        titulo = nomes[index_nome]
        titulo = titulo['href']
        titulo = titulo.replace('?ref_=fn_al_tt_1', '')
        titulo = f'https://www.imdb.com/{titulo}'
        titulos.append(titulo)
        ###subprocess.run([chrome_path, titulo])
    else:
        titulos.append("----")


## Loop para obter a nota de cada filme:
notas = []

for titulo in titulos:
    if titulo != "----":
        pagina = titulo
        resposta = requests.get(pagina, headers=cabecalho)
        soup = BeautifulSoup(resposta.content, 'html.parser')
        nota = soup.find('span', {'class': 'sc-d541859f-1 imUuxf'})
        if nota != None:
            nota = nota.get_text()
            notas.append(nota)
        else:
            notas.append("")
    else:
        notas.append("")


# Exportar lista de notas para um arquivo .csv:
df = pd.DataFrame(notas, columns=['Nota'])
df.to_csv('notas_imdb.csv', index=True)
